import { getFirestore } from 'firebase-admin/firestore'
import type { Request, Response } from 'express'
import type { Permission, Role } from '../../modules/rbac/rbac.types'

const rolesDefinition: Record<Role, Record<Permission, boolean>> = {
  owner: {
    'events.create': true,
    'events.edit': true,
    'events.publish': true,
    'events.archive': true,
    'posts.create': true,
    'posts.edit': true,
    'posts.publish': true,
    'posts.archive': true,
    'announcements.create': true,
    'announcements.edit': true,
    'announcements.publish': true,
    'announcements.archive': true,
    'pages.edit': true,
    'homeBlocks.edit': true,
    'partners.create': true,
    'partners.edit': true,
    'media.upload': true,
    'contact.read': true,
    'audit.read': true,
    'versions.read': true,
    'versions.restore': true,
    'adminUsers.manage': true,
    'system.rebuild': true,
  },
  admin: {
    'events.create': true,
    'events.edit': true,
    'events.publish': true,
    'events.archive': true,
    'posts.create': true,
    'posts.edit': true,
    'posts.publish': true,
    'posts.archive': true,
    'announcements.create': true,
    'announcements.edit': true,
    'announcements.publish': true,
    'announcements.archive': true,
    'pages.edit': true,
    'homeBlocks.edit': true,
    'partners.create': true,
    'partners.edit': true,
    'media.upload': true,
    'contact.read': true,
    'audit.read': true,
    'versions.read': true,
    'versions.restore': true,
    'adminUsers.manage': true,
    'system.rebuild': false,
  },
  editor: {
    'events.create': true,
    'events.edit': true,
    'events.publish': true,
    'events.archive': true,
    'posts.create': true,
    'posts.edit': true,
    'posts.publish': true,
    'posts.archive': true,
    'announcements.create': true,
    'announcements.edit': true,
    'announcements.publish': true,
    'announcements.archive': true,
    'pages.edit': false,
    'homeBlocks.edit': false,
    'partners.create': false,
    'partners.edit': false,
    'media.upload': true,
    'contact.read': false,
    'audit.read': false,
    'versions.read': true,
    'versions.restore': false,
    'adminUsers.manage': false,
    'system.rebuild': false,
  },
  media_manager: {
    'events.create': false,
    'events.edit': false,
    'events.publish': false,
    'events.archive': false,
    'posts.create': false,
    'posts.edit': false,
    'posts.publish': false,
    'posts.archive': false,
    'announcements.create': false,
    'announcements.edit': false,
    'announcements.publish': false,
    'announcements.archive': false,
    'pages.edit': false,
    'homeBlocks.edit': false,
    'partners.create': false,
    'partners.edit': false,
    'media.upload': true,
    'contact.read': false,
    'audit.read': false,
    'versions.read': false,
    'versions.restore': false,
    'adminUsers.manage': false,
    'system.rebuild': false,
  },
  inbox_viewer: {
    'events.create': false,
    'events.edit': false,
    'events.publish': false,
    'events.archive': false,
    'posts.create': false,
    'posts.edit': false,
    'posts.publish': false,
    'posts.archive': false,
    'announcements.create': false,
    'announcements.edit': false,
    'announcements.publish': false,
    'announcements.archive': false,
    'pages.edit': false,
    'homeBlocks.edit': false,
    'partners.create': false,
    'partners.edit': false,
    'media.upload': false,
    'contact.read': true,
    'audit.read': false,
    'versions.read': false,
    'versions.restore': false,
    'adminUsers.manage': false,
    'system.rebuild': false,
  },
}

export async function seedRoles(_req: Request, res: Response): Promise<void> {
  const db = getFirestore()
  const batch = db.batch()

  for (const [roleId, permissions] of Object.entries(rolesDefinition)) {
    const ref = db.collection('roles').doc(roleId)
    batch.set(ref, {
      name: roleId,
      permissions,
      updatedAt: new Date(),
    })
  }

  await batch.commit()

  res.status(200).json({
    success: true,
    data: {
      message: 'Roles seeded successfully',
      roles: Object.keys(rolesDefinition),
    },
  })
}
